## 1-D array

In [1]:
import numpy as np

In [4]:
a = np.array([3,2, 5,6])
type(a)

numpy.ndarray

In [63]:
# it will convert into float value
np.array([3, 6, 8, 4.2, 3, 2.3, 2.3, 8.09, ])

array([3.  , 6.  , 8.  , 4.2 , 3.  , 2.3 , 2.3 , 8.09])

In [11]:
print(len(b))
print(type(b)) # both vector and matrix belong to ndarray class

3
<class 'numpy.ndarray'>


In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.empty(3)

array([7.94457559e-321, 9.45695435e-308, 1.24611470e-306])

In [21]:
#with range of elements
e = np.arange(6) # 6 is exclusive
e

array([0, 1, 2, 3, 4, 5])

In [24]:
# with specific range of elements
e = np.arange(2 , 10)
e


array([2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
e

array([2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# continue with interval
e = np.arange(3, 21, 4)
print(e)

[ 3  7 11 15 19]


In [31]:
# linearly space arrays
e = np.linspace(2, 10, num=6)
print(e)

[ 2.   3.6  5.2  6.8  8.4 10. ]


* **specific data types in array**

In [36]:
# specific data types in array
i = np.ones(5, dtype =np.int8) 
i

array([1, 1, 1, 1, 1], dtype=int8)

In [40]:
np.ones(5, dtype = np.float16)

array([1., 1., 1., 1., 1.], dtype=float16)

## 2-D array

In [43]:
a = np.zeros((3, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [46]:
np.ones((6, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [47]:
np.empty((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
a1 = np.array([[2, 4, 8, 9], [2, 3, 4, 4], [10, 11, 33, 6]])
a1

array([[ 2,  4,  8,  9],
       [ 2,  3,  4,  4],
       [10, 11, 33,  6]])

In [74]:
a1.ndim # ndim is used for finding the dimension of an array

2

In [55]:
b1 = np.array([[3, 2, 2, 2], [30, 22, 19, 90], [97, 2, 3, 2]])
b1

array([[ 3,  2,  2,  2],
       [30, 22, 19, 90],
       [97,  2,  3,  2]])

In [70]:
# Concatenate two arrays
print(np.concatenate((a1, b1), axis = 0))
print('\n\n')
print(np.concatenate((a1, b1), axis = 1))

[[ 2  4  8  9]
 [ 2  3  4  4]
 [10 11 33  6]
 [ 3  2  2  2]
 [30 22 19 90]
 [97  2  3  2]]



[[ 2  4  8  9  3  2  2  2]
 [ 2  3  4  4 30 22 19 90]
 [10 11 33  6 97  2  3  2]]


## 3-D array

In [52]:
d = np.arange(24).reshape((2, 3, 4))
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [71]:
d.ndim

3

## Array functions

In [82]:
a = np.array([[2, 3, 2, 89, 90], [21, 3, 55, 43, 90],
             [33, 7, 89, 4, 90], [9, 3, 7, 5, 90]])
a

array([[ 2,  3,  2, 89, 90],
       [21,  3, 55, 43, 90],
       [33,  7, 89,  4, 90],
       [ 9,  3,  7,  5, 90]])

In [80]:
type(a)

numpy.ndarray

In [84]:
len(a) # find length of array

4

In [85]:
np.array(20, ndim = 5)

TypeError: 'ndim' is an invalid keyword argument for array()

In [91]:
a.any()
a

array([[ 2,  3,  2, 89, 90],
       [21,  3, 55, 43, 90],
       [33,  7, 89,  4, 90],
       [ 9,  3,  7,  5, 90]])

In [90]:
t = a.transpose()
t

array([[ 2, 21, 33,  9],
       [ 3,  3,  7,  3],
       [ 2, 55, 89,  7],
       [89, 43,  4,  5],
       [90, 90, 90, 90]])

In [93]:
s = np.arange(8)
s

array([0, 1, 2, 3, 4, 5, 6, 7])

In [97]:
# split array into sub array
np.split(s, 4)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]

In [115]:
# insert element into specific point
np.insert(s, 0, 90, axis=0)


array([90,  0,  1,  2,  3,  4,  5,  6,  7])

In [117]:
#to find the size of an array
a.size 

20

In [118]:
a.shape

(4, 5)

In [119]:
s.shape

(8,)

In [121]:
# reshape array
a = np.arange(9)  # 3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
a.reshape(3, 3)  # 3*3 = 9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
# reshape are into new shape
np.reshape(a, newshape=(3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
# Conversion into d/f dimensions

# row wise dimension
b = a[np.newaxis, : ]
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [129]:
b.shape  # now b became 2-D array

(1, 9)

In [138]:
# column wise dimension
c = a[:, np.newaxis ]
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [139]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

##### Array indexing and slicing

In [141]:
a[2]

2

In [143]:
a[8]

8

In [144]:
# slicing
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
a[2 : ]

array([2, 3, 4, 5, 6, 7, 8])

In [148]:
a[ : 5]

array([0, 1, 2, 3, 4])

In [158]:
a[-4 : -1]

array([5, 6, 7])

In [159]:
a.size

9

In [164]:
a[:,np.newaxis]


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [167]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.
